name: "Kpt Live - KinD Tests"
on:
  - workflow_dispatch

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Pinned to Commit to ensure action is consistent: https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
      # If you upgrade this version confirm the changes match your expectations
      - uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
        with:
          version: "v0.9.0"
          skipClusterCreation: true
      - name: Cluster Info
        run: |
          ./e2e/live/end-to-end-test.sh