# Copyright 2022 The kpt Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Porch End-to-End Tests
on:
  push:
    paths-ignore:
      - "docs/**"
      - "site/**"
      - "demos/**"
      - "Formula/**"
      - "mdtogo/**"
      - "package-examples/**"
      - "release/**"
      - "scripts/**"
      - "commands/**"
      - "internal/cmd**"
      - "porch/docs/**"
      - "porch/config/samples/**"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "site/**"
      - "demos/**"
      - "Formula/**"
      - "mdtogo/**"
      - "package-examples/**"
      - "release/**"
      - "scripts/**"
      - "commands/**"
      - "internal/cmd**"
      - "porch/docs/**"
      - "porch/config/samples/**"

jobs:
  tests:
    name: Porch End-to-End Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9"

    steps:
      - name: Free up disk space
        run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.5'
      - name: Checkout Porch
        uses: actions/checkout@v3
      - name: Build kpt
        run: go install .
      - name: Build Docker Images
        run: IMAGE_REPO=porch-kind IMAGE_TAG=${GITHUB_SHA:0:8} make build-images
        working-directory: ./porch
      - name: Install KinD
        uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
        with:
          version: "v0.13.0"
          image: ${{ matrix.image }}
      - name: Load Images
        run: |
          kind load docker-image porch-kind/porch-server:${GITHUB_SHA:0:8}
          kind load docker-image porch-kind/porch-controllers:${GITHUB_SHA:0:8}
          kind load docker-image porch-kind/porch-function-runner:${GITHUB_SHA:0:8}
          kind load docker-image porch-kind/porch-wrapper-server:${GITHUB_SHA:0:8}
          kind load docker-image porch-kind/test-git-server:${GITHUB_SHA:0:8}
      - name: Install Porch
        run: |
          echo ${KUBECONFIG}
          IMAGE_REPO=porch-kind IMAGE_TAG=${GITHUB_SHA:0:8} make deployment-config
          kubectl apply --wait --recursive --filename ./.build/deploy
          kubectl rollout status deployment function-runner --namespace porch-system
          kubectl rollout status deployment porch-controllers --namespace porch-system
          kubectl rollout status deployment porch-server --namespace porch-system
        working-directory: ./porch
      - name: Wait For Server
        run: |
          for i in {1..10}; do
            sleep $i
            if kubectl api-resources; then
              echo "Server is up"
              break
            fi
          done
      - name: e2e test
        run: E2E=1 go test -v -timeout 20m .
        working-directory: ./porch/test/e2e
      - name: Porch CLI e2e test
        run: make test-porch
      - name: porch e2e logs
        if: always()
        run: |
          name=$(kubectl -n porch-system get pod -l app=porch-server -o custom-columns=NAME:.metadata.name --no-headers=true)
          kubectl -n porch-system logs $name > porch-e2e-server.log
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: porch-e2e-server.log
          path: porch-e2e-server.log
